apiVersion: v1
kind: Service
metadata:
  name: {{ include "wso2amhelm.fullname" . }}
  labels:
    {{- include "wso2amhelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30133
  selector:
    {{- include "wso2amhelm.selectorLabels" . | nindent 4 }}
